package euler;

import static util.PrettyPrint.printResult;
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * 
 * Link: https://projecteuler.net/problem=2
 * @author abijwe
 */
public class Problem002 {

    public static void main(String[] args) {
        long MAX = 4000000;
        int num1 = 1;
        int num2 = 1;
        int result = 0;
        int num3 = 0;
        int count = 0;

        while(num3 < MAX) {
            num3 = num1 + num2;

            count = count == 3 ? 0 : count;
            result = count == 0 ? result + num3 : result;
            count++; num1 = num2; num2 = num3;
        }
        printResult(result);
    }
}